### ISSUE TITLE
Notification list local time zone

### ISSUE THREAD

**Issue by mohsinalimat** [muhdmirzamz/Prayers#1]
Hello,

can you please guide me on Notification list local time zone?

**Comment by muhdmirzamz** [comment]
Hi @mohsinalimat , 

I shall just refer to your email which contains this question "How to set local notification in local time zone not in UTC?"

If I'm not wrong, I set local notifications in UTC, hence your question. The one thing about dates that I learnt during this project is that the only time your dates are in "local" timezone is when you convert it to a string. At least for Swift, I don't know about other languages. 

If you were to run the demo, which I assume you did, the notification is going to fire at your local time. 

I guess to make it clearer, you can think of it as 
1) You receive the original UTC time
2) Convert it to local (and by converting, it would still show UTC, but it is your local time, in UTC, if that makes sense)
3) Setup local notifications using UTC (This is your local time in UTC, not the original UTC)

Sorry if this ran a little long, but I hope you get the concept. Feel free to ask me if you have any more questions.
